export type OfficialCategoryOption = { value: string; label: string; };
export type OfficialCategoryGroup = { slug: string; bucket: string; label: string; sourceFile: string; options: OfficialCategoryOption[]; };

export const officialCategoryGroups: OfficialCategoryGroup[] = [
  {
    slug: 'arts-and-crafts-tth',
    bucket: 'arts-crafts',
    label: 'Arts, Crafts & Sewing',
    sourceFile: 'arts-and-crafts_browse_tree_guide._TTH_.xls',
    options: [
      { value: 'arts-crafts__root-arts-and-crafts-tth', label: 'Arts, Crafts & Sewing' },
      { value: 'arts-crafts__beading-jewelry-making', label: 'Arts, Crafts & Sewing / Beading & Jewelry Making' },
      { value: 'arts-crafts__crafting', label: 'Arts, Crafts & Sewing / Crafting' },
      { value: 'arts-crafts__fabric', label: 'Arts, Crafts & Sewing / Fabric' },
      { value: 'arts-crafts__fabric-decorating', label: 'Arts, Crafts & Sewing / Fabric Decorating' },
      { value: 'arts-crafts__gift-wrapping-supplies', label: 'Arts, Crafts & Sewing / Gift Wrapping Supplies' },
      { value: 'arts-crafts__knitting-crochet', label: 'Arts, Crafts & Sewing / Knitting & Crochet' },
      { value: 'arts-crafts__model-hobby-building', label: 'Arts, Crafts & Sewing / Model & Hobby Building' },
      { value: 'arts-crafts__needlework', label: 'Arts, Crafts & Sewing / Needlework' },
      { value: 'arts-crafts__organization-storage-transport', label: 'Arts, Crafts & Sewing / Organization, Storage & Transport' },
      { value: 'arts-crafts__painting-drawing-art-supplies', label: 'Arts, Crafts & Sewing / Painting, Drawing & Art Supplies' },
      { value: 'arts-crafts__party-decorations-supplies', label: 'Arts, Crafts & Sewing / Party Decorations & Supplies' },
      { value: 'arts-crafts__printmaking', label: 'Arts, Crafts & Sewing / Printmaking' },
      { value: 'arts-crafts__scrapbooking-stamping', label: 'Arts, Crafts & Sewing / Scrapbooking & Stamping' },
      { value: 'arts-crafts__sewing', label: 'Arts, Crafts & Sewing / Sewing' },
    ],
  },
  {
    slug: 'automotive',
    bucket: 'automotive',
    label: 'Automotive',
    sourceFile: 'automotive_browse_tree_guide.xls',
    options: [
      { value: 'automotive__root-automotive', label: 'Automotive' },
      { value: 'automotive__car-care', label: 'Automotive / Car Care' },
      { value: 'automotive__car-electronics-accessories', label: 'Automotive / Car Electronics & Accessories' },
      { value: 'automotive__exterior-accessories', label: 'Automotive / Exterior Accessories' },
      { value: 'automotive__interior-accessories', label: 'Automotive / Interior Accessories' },
      { value: 'automotive__lights-bulbs-indicators', label: 'Automotive / Lights, Bulbs & Indicators' },
      { value: 'automotive__motorcycle-powersports', label: 'Automotive / Motorcycle & Powersports' },
      { value: 'automotive__oils-fluids', label: 'Automotive / Oils & Fluids' },
      { value: 'automotive__paint-paint-supplies', label: 'Automotive / Paint & Paint Supplies' },
      { value: 'automotive__performance-parts-accessories', label: 'Automotive / Performance Parts & Accessories' },
      { value: 'automotive__rv-parts-accessories', label: 'Automotive / RV Parts & Accessories' },
      { value: 'automotive__replacement-parts', label: 'Automotive / Replacement Parts' },
      { value: 'automotive__tires-wheels', label: 'Automotive / Tires & Wheels' },
      { value: 'automotive__tools-equipment', label: 'Automotive / Tools & Equipment' },
    ],
  },
  {
    slug: 'baby-products',
    bucket: 'baby',
    label: 'Baby Products',
    sourceFile: 'baby-products_browse_tree_guide.xls',
    options: [
      { value: 'baby__root-baby-products', label: 'Baby Products' },
      { value: 'baby__activity-entertainment', label: 'Baby Products / Activity & Entertainment' },
      { value: 'baby__apparel-accessories', label: 'Baby Products / Apparel & Accessories' },
      { value: 'baby__baby-toddler-toys', label: 'Baby Products / Baby & Toddler Toys' },
      { value: 'baby__baby-care', label: 'Baby Products / Baby Care' },
      { value: 'baby__baby-stationery', label: 'Baby Products / Baby Stationery' },
      { value: 'baby__car-seats-accessories', label: 'Baby Products / Car Seats & Accessories' },
      { value: 'baby__diapering', label: 'Baby Products / Diapering' },
      { value: 'baby__feeding', label: 'Baby Products / Feeding' },
      { value: 'baby__gifts', label: 'Baby Products / Gifts' },
      { value: 'baby__nursery', label: 'Baby Products / Nursery' },
      { value: 'baby__potty-training', label: 'Baby Products / Potty Training' },
      { value: 'baby__pregnancy-maternity', label: 'Baby Products / Pregnancy & Maternity' },
      { value: 'baby__safety', label: 'Baby Products / Safety' },
      { value: 'baby__strollers-accessories', label: 'Baby Products / Strollers & Accessories' },
      { value: 'baby__travel-gear', label: 'Baby Products / Travel Gear' },
    ],
  },
  {
    slug: 'beauty',
    bucket: 'beauty',
    label: 'Beauty & Personal Care',
    sourceFile: 'beauty_browse_tree_guide.xls',
    options: [
      { value: 'beauty__root-beauty', label: 'Beauty & Personal Care' },
      { value: 'beauty__foot-hand-nail-care', label: 'Beauty & Personal Care / Foot, Hand & Nail Care' },
      { value: 'beauty__fragrance', label: 'Beauty & Personal Care / Fragrance' },
      { value: 'beauty__hair-care', label: 'Beauty & Personal Care / Hair Care' },
      { value: 'beauty__makeup', label: 'Beauty & Personal Care / Makeup' },
      { value: 'beauty__personal-care', label: 'Beauty & Personal Care / Personal Care' },
      { value: 'beauty__salon-spa-equipment', label: 'Beauty & Personal Care / Salon & Spa Equipment' },
      { value: 'beauty__shave-hair-removal', label: 'Beauty & Personal Care / Shave & Hair Removal' },
      { value: 'beauty__skin-care', label: 'Beauty & Personal Care / Skin Care' },
      { value: 'beauty__tools-accessories', label: 'Beauty & Personal Care / Tools & Accessories' },
    ],
  },
  {
    slug: 'books',
    bucket: 'books',
    label: 'Books',
    sourceFile: 'books_browse_tree_guide.xls',
    options: [
      { value: 'books__root-books', label: 'Books' },
      { value: 'books__arts-photography', label: 'Books / Arts & Photography' },
      { value: 'books__biographies-memoirs', label: 'Books / Biographies & Memoirs' },
      { value: 'books__business-money', label: 'Books / Business & Money' },
      { value: 'books__children-s-books', label: "Books / Children's Books" },
      { value: 'books__comics-graphic-novels', label: 'Books / Comics & Graphic Novels' },
      { value: 'books__computers-technology', label: 'Books / Computers & Technology' },
      { value: 'books__cookbooks-food-wine', label: 'Books / Cookbooks, Food & Wine' },
      { value: 'books__crafts-hobbies-home', label: 'Books / Crafts, Hobbies & Home' },
      { value: 'books__education-teaching', label: 'Books / Education & Teaching' },
      { value: 'books__engineering-transportation', label: 'Books / Engineering & Transportation' },
      { value: 'books__health-fitness-dieting', label: 'Books / Health, Fitness & Dieting' },
      { value: 'books__history', label: 'Books / History' },
      { value: 'books__lgbtq-books', label: 'Books / LGBTQ+ Books' },
      { value: 'books__medical-books', label: 'Books / Medical Books' },
      { value: 'books__mystery-thriller-suspense', label: 'Books / Mystery, Thriller & Suspense' },
      { value: 'books__parenting-relationships', label: 'Books / Parenting & Relationships' },
      { value: 'books__politics-social-sciences', label: 'Books / Politics & Social Sciences' },
      { value: 'books__reference', label: 'Books / Reference' },
      { value: 'books__religion-spirituality', label: 'Books / Religion & Spirituality' },
      { value: 'books__romance', label: 'Books / Romance' },
      { value: 'books__science-math', label: 'Books / Science & Math' },
      { value: 'books__science-fiction-fantasy', label: 'Books / Science Fiction & Fantasy' },
      { value: 'books__self-help', label: 'Books / Self-Help' },
      { value: 'books__teen-young-adult', label: 'Books / Teen & Young Adult' },
      { value: 'books__test-preparation', label: 'Books / Test Preparation' },
      { value: 'books__travel', label: 'Books / Travel' },
    ],
  },
  {
    slug: 'cell-phones',
    bucket: 'electronics',
    label: 'Cell Phones & Accessories',
    sourceFile: 'cell-phones_browse_tree_guide.xls',
    options: [
      { value: 'electronics__root-cell-phones', label: 'Cell Phones & Accessories' },
      { value: 'electronics__accessories', label: 'Cell Phones & Accessories / Accessories' },
      { value: 'electronics__cases-holsters-sleeves', label: 'Cell Phones & Accessories / Cases, Holsters & Sleeves' },
      { value: 'electronics__cell-phones', label: 'Cell Phones & Accessories / Cell Phones' },
      { value: 'electronics__sim-cards-prepaid-minutes', label: 'Cell Phones & Accessories / SIM Cards & Prepaid Minutes' },
    ],
  },
  {
    slug: 'electronics',
    bucket: 'electronics',
    label: 'Electronics',
    sourceFile: 'electronics_browse_tree_guide.xls',
    options: [
      { value: 'electronics__root-electronics', label: 'Electronics' },
      { value: 'electronics__accessories-supplies', label: 'Electronics / Accessories & Supplies' },
      { value: 'electronics__camera-photo', label: 'Electronics / Camera & Photo' },
      { value: 'electronics__car-vehicle-electronics', label: 'Electronics / Car & Vehicle Electronics' },
      { value: 'electronics__cell-phones-accessories', label: 'Electronics / Cell Phones & Accessories' },
      { value: 'electronics__computers-accessories', label: 'Electronics / Computers & Accessories' },
      { value: 'electronics__gps-finders-accessories', label: 'Electronics / GPS, Finders & Accessories' },
      { value: 'electronics__headphones-earbuds-accessories', label: 'Electronics / Headphones, Earbuds & Accessories' },
      { value: 'electronics__home-audio', label: 'Electronics / Home Audio' },
      { value: 'electronics__household-batteries-chargers-accessories', label: 'Electronics / Household Batteries, Chargers & Accessories' },
      { value: 'electronics__office-electronics', label: 'Electronics / Office Electronics' },
      { value: 'electronics__portable-audio-video', label: 'Electronics / Portable Audio & Video' },
      { value: 'electronics__power-accessories', label: 'Electronics / Power Accessories' },
      { value: 'electronics__security-surveillance', label: 'Electronics / Security & Surveillance' },
      { value: 'electronics__tablets', label: 'Electronics / Tablets' },
      { value: 'electronics__television-video', label: 'Electronics / Television & Video' },
      { value: 'electronics__video-projectors', label: 'Electronics / Video Projectors' },
      { value: 'electronics__wearable-technology', label: 'Electronics / Wearable Technology' },
      { value: 'electronics__ebook-readers-accessories', label: 'Electronics / eBook Readers & Accessories' },
    ],
  },
  {
    slug: 'fashion',
    bucket: 'fashion',
    label: 'Clothing, Shoes & Jewelry',
    sourceFile: 'fashion_browse_tree_guide.xls',
    options: [
      { value: 'fashion__root-fashion', label: 'Clothing, Shoes & Jewelry' },
      { value: 'fashion__baby', label: 'Clothing, Shoes & Jewelry / Baby' },
      { value: 'fashion__boys', label: 'Clothing, Shoes & Jewelry / Boys' },
      { value: 'fashion__costumes-accessories', label: 'Clothing, Shoes & Jewelry / Costumes & Accessories' },
      { value: 'fashion__girls', label: 'Clothing, Shoes & Jewelry / Girls' },
      { value: 'fashion__luggage-travel-gear', label: 'Clothing, Shoes & Jewelry / Luggage & Travel Gear' },
      { value: 'fashion__men', label: 'Clothing, Shoes & Jewelry / Men' },
      { value: 'fashion__novelty-more', label: 'Clothing, Shoes & Jewelry / Novelty & More' },
      { value: 'fashion__shoe-jewelry-watch-accessories', label: 'Clothing, Shoes & Jewelry / Shoe, Jewelry & Watch Accessories' },
      { value: 'fashion__sport-specific-clothing', label: 'Clothing, Shoes & Jewelry / Sport Specific Clothing' },
      { value: 'fashion__traditional-cultural-wear', label: 'Clothing, Shoes & Jewelry / Traditional & Cultural Wear' },
      { value: 'fashion__uniforms-work-safety', label: 'Clothing, Shoes & Jewelry / Uniforms, Work & Safety' },
      { value: 'fashion__women', label: 'Clothing, Shoes & Jewelry / Women' },
    ],
  },
  {
    slug: 'garden',
    bucket: 'garden',
    label: 'Patio, Lawn & Garden',
    sourceFile: 'garden_browse_tree_guide.xls',
    options: [
      { value: 'garden__root-garden', label: 'Patio, Lawn & Garden' },
      { value: 'garden__farm-ranch', label: 'Patio, Lawn & Garden / Farm & Ranch' },
      { value: 'garden__gardening-lawn-care', label: 'Patio, Lawn & Garden / Gardening & Lawn Care' },
      { value: 'garden__generators-portable-power', label: 'Patio, Lawn & Garden / Generators & Portable Power' },
      { value: 'garden__grills-outdoor-cooking', label: 'Patio, Lawn & Garden / Grills & Outdoor Cooking' },
      { value: 'garden__outdoor-d-cor', label: 'Patio, Lawn & Garden / Outdoor Décor' },
      { value: 'garden__outdoor-heating-cooling', label: 'Patio, Lawn & Garden / Outdoor Heating & Cooling' },
      { value: 'garden__outdoor-lighting', label: 'Patio, Lawn & Garden / Outdoor Lighting' },
      { value: 'garden__outdoor-power-tools', label: 'Patio, Lawn & Garden / Outdoor Power Tools' },
      { value: 'garden__outdoor-storage-housing', label: 'Patio, Lawn & Garden / Outdoor Storage & Housing' },
      { value: 'garden__patio-furniture-accessories', label: 'Patio, Lawn & Garden / Patio Furniture & Accessories' },
      { value: 'garden__pest-control', label: 'Patio, Lawn & Garden / Pest Control' },
      { value: 'garden__pools-hot-tubs-supplies', label: 'Patio, Lawn & Garden / Pools, Hot Tubs & Supplies' },
      { value: 'garden__snow-removal', label: 'Patio, Lawn & Garden / Snow Removal' },
    ],
  },
  {
    slug: 'grocery-tth',
    bucket: 'grocery',
    label: 'Grocery & Gourmet Food',
    sourceFile: 'grocery_browse_tree_guide._TTH_.xls',
    options: [
      { value: 'grocery__root-grocery-tth', label: 'Grocery & Gourmet Food' },
      { value: 'grocery__alcoholic-beverages', label: 'Grocery & Gourmet Food / Alcoholic Beverages' },
      { value: 'grocery__baby-foods', label: 'Grocery & Gourmet Food / Baby Foods' },
      { value: 'grocery__beverages', label: 'Grocery & Gourmet Food / Beverages' },
      { value: 'grocery__breads-bakery', label: 'Grocery & Gourmet Food / Breads & Bakery' },
      { value: 'grocery__breakfast-cereal', label: 'Grocery & Gourmet Food / Breakfast Cereal' },
      { value: 'grocery__breakfast-foods', label: 'Grocery & Gourmet Food / Breakfast Foods' },
      { value: 'grocery__dairy-eggs-plant-based-alternatives', label: 'Grocery & Gourmet Food / Dairy, Eggs & Plant-Based Alternatives' },
      { value: 'grocery__deli-prepared-foods', label: 'Grocery & Gourmet Food / Deli & Prepared Foods' },
      { value: 'grocery__food-beverage-gifts', label: 'Grocery & Gourmet Food / Food & Beverage Gifts' },
      { value: 'grocery__fresh-flowers-live-indoor-plants', label: 'Grocery & Gourmet Food / Fresh Flowers & Live Indoor Plants' },
      { value: 'grocery__fresh-meal-kits', label: 'Grocery & Gourmet Food / Fresh Meal Kits' },
      { value: 'grocery__frozen', label: 'Grocery & Gourmet Food / Frozen' },
      { value: 'grocery__home-brewing-winemaking', label: 'Grocery & Gourmet Food / Home Brewing & Winemaking' },
      { value: 'grocery__meat-seafood', label: 'Grocery & Gourmet Food / Meat & Seafood' },
      { value: 'grocery__meat-substitutes', label: 'Grocery & Gourmet Food / Meat Substitutes' },
      { value: 'grocery__pantry-staples', label: 'Grocery & Gourmet Food / Pantry Staples' },
      { value: 'grocery__produce', label: 'Grocery & Gourmet Food / Produce' },
      { value: 'grocery__snacks-sweets', label: 'Grocery & Gourmet Food / Snacks & Sweets' },
    ],
  },
  {
    slug: 'health',
    bucket: 'health',
    label: 'Health & Household',
    sourceFile: 'health_browse_tree_guide.xls',
    options: [
      { value: 'health__root-health', label: 'Health & Household' },
      { value: 'health__baby-child-care', label: 'Health & Household / Baby & Child Care' },
      { value: 'health__diet-sports-nutrition', label: 'Health & Household / Diet & Sports Nutrition' },
      { value: 'health__funeral', label: 'Health & Household / Funeral' },
      { value: 'health__health-care', label: 'Health & Household / Health Care' },
      { value: 'health__household-supplies', label: 'Health & Household / Household Supplies' },
      { value: 'health__medical-supplies-equipment', label: 'Health & Household / Medical Supplies & Equipment' },
      { value: 'health__oral-care', label: 'Health & Household / Oral Care' },
      { value: 'health__personal-care', label: 'Health & Household / Personal Care' },
      { value: 'health__sexual-wellness', label: 'Health & Household / Sexual Wellness' },
      { value: 'health__stationery-gift-wrapping-supplies', label: 'Health & Household / Stationery & Gift Wrapping Supplies' },
      { value: 'health__vision', label: 'Health & Household / Vision' },
      { value: 'health__vitamins-minerals-supplements', label: 'Health & Household / Vitamins, Minerals & Supplements' },
      { value: 'health__wellness-relaxation', label: 'Health & Household / Wellness & Relaxation' },
    ],
  },
  {
    slug: 'home-improvement',
    bucket: 'tools',
    label: 'Tools & Home Improvement',
    sourceFile: 'home-improvement_browse_tree_guide.xls',
    options: [
      { value: 'tools__root-home-improvement', label: 'Tools & Home Improvement' },
      { value: 'tools__appliances', label: 'Tools & Home Improvement / Appliances' },
      { value: 'tools__building-supplies', label: 'Tools & Home Improvement / Building Supplies' },
      { value: 'tools__electrical', label: 'Tools & Home Improvement / Electrical' },
      { value: 'tools__hardware', label: 'Tools & Home Improvement / Hardware' },
      { value: 'tools__kitchen-bath-fixtures', label: 'Tools & Home Improvement / Kitchen & Bath Fixtures' },
      { value: 'tools__light-bulbs', label: 'Tools & Home Improvement / Light Bulbs' },
      { value: 'tools__lighting-ceiling-fans', label: 'Tools & Home Improvement / Lighting & Ceiling Fans' },
      { value: 'tools__measuring-layout-tools', label: 'Tools & Home Improvement / Measuring & Layout Tools' },
      { value: 'tools__paint-wall-treatments-supplies', label: 'Tools & Home Improvement / Paint, Wall Treatments & Supplies' },
      { value: 'tools__plumbing', label: 'Tools & Home Improvement / Plumbing' },
      { value: 'tools__power-hand-tools', label: 'Tools & Home Improvement / Power & Hand Tools' },
      { value: 'tools__safety-security', label: 'Tools & Home Improvement / Safety & Security' },
      { value: 'tools__storage-home-organization', label: 'Tools & Home Improvement / Storage & Home Organization' },
      { value: 'tools__welding-soldering', label: 'Tools & Home Improvement / Welding & Soldering' },
    ],
  },
  {
    slug: 'home-kitchen-tth',
    bucket: 'home',
    label: 'Home & Kitchen',
    sourceFile: 'home-kitchen_browse_tree_guide._TTH_.xls',
    options: [
      { value: 'home__root-home-kitchen-tth', label: 'Home & Kitchen' },
      { value: 'home__bath', label: 'Home & Kitchen / Bath' },
      { value: 'home__bedding', label: 'Home & Kitchen / Bedding' },
      { value: 'home__cleaning-supplies', label: 'Home & Kitchen / Cleaning Supplies' },
      { value: 'home__event-party-supplies', label: 'Home & Kitchen / Event & Party Supplies' },
      { value: 'home__furniture', label: 'Home & Kitchen / Furniture' },
      { value: 'home__heating-cooling-air-quality', label: 'Home & Kitchen / Heating, Cooling & Air Quality' },
      { value: 'home__home-d-cor-products', label: 'Home & Kitchen / Home Décor Products' },
      { value: 'home__irons-steamers', label: 'Home & Kitchen / Irons & Steamers' },
      { value: 'home__kids-home-store', label: "Home & Kitchen / Kids' Home Store" },
      { value: 'home__kitchen-dining', label: 'Home & Kitchen / Kitchen & Dining' },
      { value: 'home__lighting-ceiling-fans', label: 'Home & Kitchen / Lighting & Ceiling Fans' },
      { value: 'home__seasonal-d-cor', label: 'Home & Kitchen / Seasonal Décor' },
      { value: 'home__storage-organization', label: 'Home & Kitchen / Storage & Organization' },
      { value: 'home__vacuums-floor-care', label: 'Home & Kitchen / Vacuums & Floor Care' },
      { value: 'home__wall-art', label: 'Home & Kitchen / Wall Art' },
    ],
  },
  {
    slug: 'industrial-tth',
    bucket: 'industrial',
    label: 'Industrial & Scientific',
    sourceFile: 'industrial_browse_tree_guide._TTH_.xls',
    options: [
      { value: 'industrial__root-industrial-tth', label: 'Industrial & Scientific' },
      { value: 'industrial__abrasive-finishing-products', label: 'Industrial & Scientific / Abrasive & Finishing Products' },
      { value: 'industrial__additive-manufacturing-products', label: 'Industrial & Scientific / Additive Manufacturing Products' },
      { value: 'industrial__adhesives-sealants-lubricants', label: 'Industrial & Scientific / Adhesives, Sealants & Lubricants' },
      { value: 'industrial__commercial-door-products', label: 'Industrial & Scientific / Commercial Door Products' },
      { value: 'industrial__commercial-lighting', label: 'Industrial & Scientific / Commercial Lighting' },
      { value: 'industrial__cutting-tools', label: 'Industrial & Scientific / Cutting Tools' },
      { value: 'industrial__digital-signage', label: 'Industrial & Scientific / Digital Signage' },
      { value: 'industrial__fasteners', label: 'Industrial & Scientific / Fasteners' },
      { value: 'industrial__filtration', label: 'Industrial & Scientific / Filtration' },
      { value: 'industrial__food-service-equipment-supplies', label: 'Industrial & Scientific / Food Service Equipment & Supplies' },
      { value: 'industrial__hydraulics-pneumatics-plumbing', label: 'Industrial & Scientific / Hydraulics, Pneumatics & Plumbing' },
      { value: 'industrial__industrial-electrical', label: 'Industrial & Scientific / Industrial Electrical' },
      { value: 'industrial__industrial-hardware', label: 'Industrial & Scientific / Industrial Hardware' },
      { value: 'industrial__janitorial-sanitation-supplies', label: 'Industrial & Scientific / Janitorial & Sanitation Supplies' },
      { value: 'industrial__lab-scientific-products', label: 'Industrial & Scientific / Lab & Scientific Products' },
      { value: 'industrial__material-handling-products', label: 'Industrial & Scientific / Material Handling Products' },
      { value: 'industrial__occupational-health-safety-products', label: 'Industrial & Scientific / Occupational Health & Safety Products' },
      { value: 'industrial__packaging-shipping-supplies', label: 'Industrial & Scientific / Packaging & Shipping Supplies' },
      { value: 'industrial__power-hand-tools', label: 'Industrial & Scientific / Power & Hand Tools' },
      { value: 'industrial__power-transmission-products', label: 'Industrial & Scientific / Power Transmission Products' },
      { value: 'industrial__professional-dental-supplies', label: 'Industrial & Scientific / Professional Dental Supplies' },
      { value: 'industrial__professional-medical-supplies', label: 'Industrial & Scientific / Professional Medical Supplies' },
      { value: 'industrial__raw-materials', label: 'Industrial & Scientific / Raw Materials' },
      { value: 'industrial__retail-store-fixtures-equipment', label: 'Industrial & Scientific / Retail Store Fixtures & Equipment' },
      { value: 'industrial__robotics', label: 'Industrial & Scientific / Robotics' },
      { value: 'industrial__science-education', label: 'Industrial & Scientific / Science Education' },
      { value: 'industrial__test-measure-inspect', label: 'Industrial & Scientific / Test, Measure & Inspect' },
    ],
  },
  {
    slug: 'jewelry',
    bucket: 'jewelry',
    label: 'Jewelry',
    sourceFile: 'jewelry_browse_tree_guide.xls',
    options: [
      { value: 'jewelry__root-jewelry', label: 'Jewelry' },
      { value: 'jewelry__accessories', label: 'Jewelry / Accessories' },
      { value: 'jewelry__boys', label: 'Jewelry / Boys' },
      { value: 'jewelry__girls', label: 'Jewelry / Girls' },
      { value: 'jewelry__loose-gemstones', label: 'Jewelry / Loose Gemstones' },
      { value: 'jewelry__men', label: 'Jewelry / Men' },
      { value: 'jewelry__novelty-more', label: 'Jewelry / Novelty & More' },
      { value: 'jewelry__women', label: 'Jewelry / Women' },
    ],
  },
  {
    slug: 'musical-instruments-tth',
    bucket: 'musical-instruments',
    label: 'Musical Instruments',
    sourceFile: 'musical-instruments_browse_tree_guide._TTH_.xls',
    options: [
      { value: 'musical-instruments__root-musical-instruments-tth', label: 'Musical Instruments' },
      { value: 'musical-instruments__amplifiers-effects', label: 'Musical Instruments / Amplifiers & Effects' },
      { value: 'musical-instruments__band-orchestra', label: 'Musical Instruments / Band & Orchestra' },
      { value: 'musical-instruments__bass-guitars', label: 'Musical Instruments / Bass Guitars' },
      { value: 'musical-instruments__drums-percussion', label: 'Musical Instruments / Drums & Percussion' },
      { value: 'musical-instruments__electronic-music-dj-karaoke', label: 'Musical Instruments / Electronic Music, DJ & Karaoke' },
      { value: 'musical-instruments__guitars', label: 'Musical Instruments / Guitars' },
      { value: 'musical-instruments__instrument-accessories', label: 'Musical Instruments / Instrument Accessories' },
      { value: 'musical-instruments__keyboards-midi', label: 'Musical Instruments / Keyboards & MIDI' },
      { value: 'musical-instruments__live-sound-stage', label: 'Musical Instruments / Live Sound & Stage' },
      { value: 'musical-instruments__microphones-accessories', label: 'Musical Instruments / Microphones & Accessories' },
      { value: 'musical-instruments__scores-songbooks-lyrics', label: 'Musical Instruments / Scores, Songbooks & Lyrics' },
      { value: 'musical-instruments__stringed-instruments', label: 'Musical Instruments / Stringed Instruments' },
      { value: 'musical-instruments__studio-recording-equipment', label: 'Musical Instruments / Studio Recording Equipment' },
      { value: 'musical-instruments__ukuleles-mandolins-banjos', label: 'Musical Instruments / Ukuleles, Mandolins & Banjos' },
      { value: 'musical-instruments__wind-woodwind-instruments', label: 'Musical Instruments / Wind & Woodwind Instruments' },
    ],
  },
  {
    slug: 'office-products',
    bucket: 'office',
    label: 'Office Products',
    sourceFile: 'office-products_browse_tree_guide.xls',
    options: [
      { value: 'office__root-office-products', label: 'Office Products' },
      { value: 'office__office-school-supplies', label: 'Office Products / Office & School Supplies' },
      { value: 'office__office-electronics', label: 'Office Products / Office Electronics' },
      { value: 'office__office-furniture-lighting', label: 'Office Products / Office Furniture & Lighting' },
    ],
  },
  {
    slug: 'pet-supplies',
    bucket: 'pet',
    label: 'Pet Supplies',
    sourceFile: 'pet-supplies_browse_tree_guide.xls',
    options: [
      { value: 'pet__root-pet-supplies', label: 'Pet Supplies' },
      { value: 'pet__birds', label: 'Pet Supplies / Birds' },
      { value: 'pet__cats', label: 'Pet Supplies / Cats' },
      { value: 'pet__dogs', label: 'Pet Supplies / Dogs' },
      { value: 'pet__fish-aquatic-pets', label: 'Pet Supplies / Fish & Aquatic Pets' },
      { value: 'pet__horses', label: 'Pet Supplies / Horses' },
      { value: 'pet__insects', label: 'Pet Supplies / Insects' },
      { value: 'pet__reptiles-amphibians', label: 'Pet Supplies / Reptiles & Amphibians' },
      { value: 'pet__small-animals', label: 'Pet Supplies / Small Animals' },
    ],
  },
  {
    slug: 'software',
    bucket: 'software',
    label: 'Software',
    sourceFile: 'software_browse_tree_guide.xls',
    options: [
      { value: 'software__root-software', label: 'Software' },
      { value: 'software__accounting-finance', label: 'Software / Accounting & Finance' },
      { value: 'software__antivirus-security', label: 'Software / Antivirus & Security' },
      { value: 'software__business-office', label: 'Software / Business & Office' },
      { value: 'software__children-s', label: "Software / Children's" },
      { value: 'software__education-reference', label: 'Software / Education & Reference' },
      { value: 'software__lifestyle-hobbies', label: 'Software / Lifestyle & Hobbies' },
      { value: 'software__music', label: 'Software / Music' },
      { value: 'software__networking-servers', label: 'Software / Networking & Servers' },
      { value: 'software__operating-systems', label: 'Software / Operating Systems' },
      { value: 'software__photography-graphic-design', label: 'Software / Photography & Graphic Design' },
      { value: 'software__programming-web-development', label: 'Software / Programming & Web Development' },
      { value: 'software__tax-preparation', label: 'Software / Tax Preparation' },
      { value: 'software__utilities', label: 'Software / Utilities' },
      { value: 'software__video', label: 'Software / Video' },
    ],
  },
  {
    slug: 'sporting-goods-tth',
    bucket: 'sports',
    label: 'Sports & Outdoors',
    sourceFile: 'sporting-goods_browse_tree_guide._TTH_.xls',
    options: [
      { value: 'sports__root-sporting-goods-tth', label: 'Sports & Outdoors' },
      { value: 'sports__clothing', label: 'Sports & Outdoors / Clothing' },
      { value: 'sports__exercise-fitness', label: 'Sports & Outdoors / Exercise & Fitness' },
      { value: 'sports__fan-shop', label: 'Sports & Outdoors / Fan Shop' },
      { value: 'sports__hunting-fishing', label: 'Sports & Outdoors / Hunting & Fishing' },
      { value: 'sports__memorabilia-display-storage', label: 'Sports & Outdoors / Memorabilia Display & Storage' },
      { value: 'sports__outdoor-recreation', label: 'Sports & Outdoors / Outdoor Recreation' },
      { value: 'sports__sports', label: 'Sports & Outdoors / Sports' },
      { value: 'sports__sports-outdoor-recreation-accessories', label: 'Sports & Outdoors / Sports & Outdoor Recreation Accessories' },
      { value: 'sports__sports-medicine', label: 'Sports & Outdoors / Sports Medicine' },
    ],
  },
  {
    slug: 'toys-and-games',
    bucket: 'toys',
    label: 'Toys & Games',
    sourceFile: 'toys-and-games_browse_tree_guide.xls',
    options: [
      { value: 'toys__root-toys-and-games', label: 'Toys & Games' },
      { value: 'toys__arts-crafts', label: 'Toys & Games / Arts & Crafts' },
      { value: 'toys__baby-toddler-toys', label: 'Toys & Games / Baby & Toddler Toys' },
      { value: 'toys__building-toys', label: 'Toys & Games / Building Toys' },
      { value: 'toys__collectible-toys', label: 'Toys & Games / Collectible Toys' },
      { value: 'toys__dolls-accessories', label: 'Toys & Games / Dolls & Accessories' },
      { value: 'toys__dress-up-pretend-play', label: 'Toys & Games / Dress Up & Pretend Play' },
      { value: 'toys__games-accessories', label: 'Toys & Games / Games & Accessories' },
      { value: 'toys__kids-electronics', label: "Toys & Games / Kids' Electronics" },
      { value: 'toys__learning-education', label: 'Toys & Games / Learning & Education' },
      { value: 'toys__novelty-gag-toys', label: 'Toys & Games / Novelty & Gag Toys' },
      { value: 'toys__party-supplies', label: 'Toys & Games / Party Supplies' },
      { value: 'toys__puppets-puppet-theaters', label: 'Toys & Games / Puppets & Puppet Theaters' },
      { value: 'toys__puzzles', label: 'Toys & Games / Puzzles' },
      { value: 'toys__remote-app-controlled-vehicles-parts', label: 'Toys & Games / Remote & App Controlled Vehicles & Parts' },
      { value: 'toys__sports-outdoor-play', label: 'Toys & Games / Sports & Outdoor Play' },
      { value: 'toys__stuffed-animals-plush-toys', label: 'Toys & Games / Stuffed Animals & Plush Toys' },
      { value: 'toys__toy-figures-playsets', label: 'Toys & Games / Toy Figures & Playsets' },
      { value: 'toys__tricycles-scooters-wagons', label: 'Toys & Games / Tricycles, Scooters & Wagons' },
      { value: 'toys__vehicles', label: 'Toys & Games / Vehicles' },
    ],
  },
  {
    slug: 'videogames',
    bucket: 'video-games',
    label: 'Video Games',
    sourceFile: 'videogames_browse_tree_guide.xls',
    options: [
      { value: 'video-games__root-videogames', label: 'Video Games' },
      { value: 'video-games__handheld-game-systems', label: 'Video Games / Handheld Game Systems' },
      { value: 'video-games__legacy-systems', label: 'Video Games / Legacy Systems' },
      { value: 'video-games__mac', label: 'Video Games / Mac' },
      { value: 'video-games__nintendo-switch', label: 'Video Games / Nintendo Switch' },
      { value: 'video-games__online-game-services', label: 'Video Games / Online Game Services' },
      { value: 'video-games__pc', label: 'Video Games / PC' },
      { value: 'video-games__playstation-4', label: 'Video Games / PlayStation 4' },
      { value: 'video-games__playstation-5', label: 'Video Games / PlayStation 5' },
      { value: 'video-games__virtual-reality', label: 'Video Games / Virtual Reality' },
      { value: 'video-games__xbox-one', label: 'Video Games / Xbox One' },
      { value: 'video-games__xbox-series-x-s', label: 'Video Games / Xbox Series X & S' },
    ],
  },
  {
    slug: 'watches',
    bucket: 'watches',
    label: 'Watches',
    sourceFile: 'watches_browse_tree_guide.xls',
    options: [
      { value: 'watches__root-watches', label: 'Watches' },
      { value: 'watches__accessories', label: 'Watches / Accessories' },
      { value: 'watches__boys', label: 'Watches / Boys' },
      { value: 'watches__girls', label: 'Watches / Girls' },
      { value: 'watches__men', label: 'Watches / Men' },
      { value: 'watches__women', label: 'Watches / Women' },
    ],
  },
];
